<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\UploadedFile;

/**
 * This is the model class for table "editorials".
 *
 * @property int $id
 * @property string|null $title
 * @property string $fullName
 * @property string $description
 * @property string $email
 * @property string $phone
 * @property integer $view_number
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Editorials extends \yii\db\ActiveRecord
{
    public $image;
    public $gallery;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'editorials';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fullName', 'description', 'view_number'], 'required'],
            [['created_at', 'updated_at', 'view_number'], 'integer'],
            [['title', 'fullName', 'email', 'phone'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 500],

            [['image'], 'file', 'extensions' => ['png', 'jpg', 'jpeg']],
            [['gallery'], 'file', 'extensions' => ['png', 'jpg', 'jpeg'], 'maxFiles' => 5],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Sarlavha',
            'fullName' => 'F.I.O.',
            'description' => 'Tavsif',
            'view_number' => 'Saytda ko\'rinish raqami',
            'phone' => 'Telefon',
            'email' => 'E-mail',
            'image' => 'Rasm',
            'gallery' => 'Galereya',
            'created_at' => 'Yaratilgan',
            'updated_at' => 'Yangilangan',
        ];
    }

    //  {----------------Image uploads BEGIN----------------}
    public function upload()
    {
        if ($this->validate()) {
            $path = Yii::getAlias('@webroot') . $this->image->baseName . '.' . $this->image->extension;
            $this->image->saveAs($path);
            $this->attachImage($path, true);
            @unlink($path);
            return true;
        } else {
            return false;
        }
    }

    public function uploadGallery()
    {
        if ($this->validate()) {
            foreach ($this->gallery as $file) {
                $path = Yii::getAlias('@webroot') . $file->baseName . '.' . $file->extension;
                $file->saveAs($path);
                $this->attachImage($path);
                @unlink($path);
            }
            return true;
        } else {
            return false;
        }
    }

    //  {----------------Image uploads END----------------}

    public function afterSave($insert, $changedAttributes)
    {
        //        rasm uchun begin
        if ($this->image = UploadedFile::getInstance($this, 'image')) {
            $this->upload();
        }
        unset($this->image);

        if ($this->gallery = UploadedFile::getInstances($this, 'gallery')) {
            $this->uploadGallery();
        }
        //        rasm uchun end

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $this->removeImages();
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
